### PR TITLE
Fix RF interaction with the Mana Fluxfield

### PR DESCRIPTION
**Pull request by KaseiFR**
I removed the unresolvable dependency to 'CoFHAPI|energy', and fix some confusion with the API Receiver/Connector sides.

I tested it against a recent version of Buildcraft.

### CODE REVIEW

**Comment by williewillus** [comment]
Did you make sure that it didn't crash when nothing providing the RF API is present? (botania alone, place the fluxfield and try giving it mana)

**Comment by KaseiFR** [comment]
As far as I understood, there was nothing more to the RF API than the API itself. No TE or hard dependency. I was obvsiously wrong ^^.
Back to the dev then.

**Comment by KaseiFR** [comment]
But even with mod providing the RF API, there no mod 'CoFHAPI|energy' loaded, I checked. What could I put in the Optional?

**Comment by GirafiStudios** [comment]
Maybe "CoFHLib" will work as the modid, since it's what is set as the owner in the @API annotation (Not sure if it will actually work). Another solutation could be to provide the whole RF API I guess.

**Comment by williewillus** [comment]
I don't want to package the RF api, that causes a bundle of issues and it's not a core component of botania - tterrag said using CoFHAPI|energy should've worked

**Comment by KaseiFR** [comment]
'CoFHAPI|energy' is provided in a subpackage of the API. But the issue is that even with a mod packing the API, `Loader.isModLoaded("CoFHAPI|energy")` still evaluate to false.
There must be another function to detect it.

**Comment by yrsegal** [comment]
isn't the API an actual jar?

**Comment by williewillus** [comment]
yes, I'd say use ModAPIManager and print out everything when buildcraft is installed and see if it's there

**Comment by KaseiFR** [comment]
There. I restored the Optional annotations, and change the mod check to an API check in the main Botania file. And then I squashed it all, so it never happenened ;)

**Comment by williewillus** [comment]
wait so was CoFHAPI|energy loaded after all?
This works completely with buildcraft, and doesn't crash when no RF API present?

**Comment by KaseiFR** [comment]
Yes, but as an API an not a mod, the previous condition in the `onUpdate` was always false.
It works both alone and with BC.

**Comment by williewillus** [comment]
Awesome, thanks!

**Comment by williewillus** [comment]
Wait wait, if addcache and transmitenergy are gated behind a mod check (Optional), which you say isn't working, then how is it working with Buildcraft?

Or does optional let you do API's?

**Comment by KaseiFR** [comment]
There are two gates: the Optional annotation, which erase code, and a manual check in the update callback, which prevent said code from being called.
The first gate prevents import error, and the second prevents calling missing methods.
At first, I saw that the manual verification wasn't working, and I assumed neither the Optional. But only the second gate was broken, not the Optional.

**Comment by williewillus** [comment]
ah awesome

**Pull request merged**
