### PR TITLE
Fix erratic colorization of bursts and flashes

### LINKED ISSUE #198: Mana Bursts are extremely rainbow
that's a white lens. The color assignment system is weird, and doesn't quite work with the flashes either. It just colorizes the rainbow more.

### PR DESCRIPTION
**Pull request by yrsegal**
closes #198

### CODE REVIEW

**Comment by yrsegal** [comment]
Since I accidentially deleted the other PR... a verdict @williewillus?

**Comment by williewillus** [comment]
It really bothers me that I can't identify what changed in the code (it happens in 1.8)
because it probably means this fixes the symptoms, not a underlying bug.
But whatever this works for now.

**Comment by yrsegal** [comment]
wait, there was something wrong because I rewrote it D:

**Comment by williewillus** [comment]
welp

**Pull request merged**
