### PR TITLE
Fix the Rod of the Terra Firma not working

### LINKED ISSUE #191: Rod of the Terra Firma doesn't work
Running FTB Unstable with this port of Botania 249 it appears that the Rod of the Terra Firma doesn't work.  Holding right click, it doesn't do it's usual thing of flattening out the vicinity with dirt.

I poked around to see if there was some mod conflict or config causing it but I can't find anything.

### PR DESCRIPTION
**Pull request by yrsegal**
Closes #191

### CODE REVIEW

**Comment by williewillus** [comment]
what was the cause?
Also get rid of all the needless import shuffling and format changes (Botania has no space between if/for/while and the open paren)

**Comment by yrsegal** [comment]
ah, sure

the cause? Well... you didn't check for air, you treated it like anything else.

Also the position needed to be offset by 1 vertically, but that was more minor.

**Comment by yrsegal** [comment]
uh... botania has a lot of space between the paren. In fact, I can find over 100 examples of both space before and space after.

**Comment by williewillus** [comment]
I'll reformat it later to get rid of them :P

**Comment by yrsegal** [comment]
ಠ_ಠ but you could do it the other way around

**Comment by williewillus** [comment]
More importantly the format changes cloud up the diff immensely, meaning I can't see where the _actual_ fix is (which probably is only 1-4 lines) without wading through lines of format changes

**Comment by yrsegal** [comment]
i'm fixing it, don't worry

**Comment by yrsegal** [comment]
fixed

**Comment by yrsegal** [comment]
it is close to 1-4 lines, if you want me to remove the other refactors (the stream and the simplification of the function) I can do that

**Comment by yrsegal** [comment]
I did that, now you can see the actual fix

**Pull request merged**
