### PR TITLE
Added oredictionary definitions for records

### PR DESCRIPTION
**Pull request by Sunconure11**

### CODE REVIEW

**Comment by williewillus** [comment]
are the vanilla records registered like this?

**Comment by yrsegal** [comment]
Nothing is actually being registered in this PR. I'd just set the two records' oredict directly without putting it in LibOreDict.
Records are oredicted as "record", willie, so the _message_ of this PR is valid.

**Comment by Sunconure11** [comment]
Fuck, so where are defintions registered then?

**Comment by Sunconure11** [comment]
Oh, I see how they are handled. Had half of it right. I will let willie handle this. But yeah, vanilla records are registered like this.

**Pull request closed without merging**
