### PR TITLE
Updated bauble/ancient will/mana tablet rendering.

### PR DESCRIPTION
**Pull request by Lomeli12**
Updated the BaubleRenderHandler to be a LayerRenderer and updated IBaubleRender to reflect the changes.

Edit: I just realized I missed the Tiny Planet, so hold on for now!

### CODE REVIEW

**Comment by williewillus** [comment]
Fix merge conflicts too, and get rid of that giant reformat diff in BaubleRenderHandler :p

**Comment by Lomeli12** [comment]
I didn't even notice that. IDEA changed all the tabs into spaces XD.

**Comment by Lomeli12** [comment]
Should be good to pull now.

**Comment by williewillus** [comment]
Also I just realized, a big portion of these already have item models - it's unnecessary and wasteful to the atlas to stitch their icon again and render it the old way, you should just render the item model using Minecraft.getMinecraft().getRenderItem().renderItem(ItemStack, TransformType.NONE) which was what I was really aiming for with these :p

Sorry for telling you now, I derped and forgot :/

It can't be a direct substitution from renderIconIn3D to renderItem since the GL state setup is different (or maybe it can be, I'm not sure)

**Comment by Lomeli12** [comment]
Got some pretty weird scaling for the cosmetic baubles using renderItem.

**Comment by williewillus** [comment]
Yeah new gl transforms will be needed

**Comment by williewillus** [comment]
I've been working on this, tracking progress at #49, so going to close this.
Sorry, but thanks for your effort anyway!

**Pull request closed without merging**
