### PR TITLE
Fix all outstanding auxiliary renders.

### LINKED ISSUE #49: Auxiliary Rendering Tracker
Tracker to help me keep track of which auxiliary renders I have confirmed rendering properly again
- [x] Contributor flowers
- [x] Phi's flower
- [x] Vazkii's twintails
- [x] haighyorkie's goldfish
- [x] mana tablets on belt
- [x] terrasteel helmet wills
- [ ] cosmetic baubles
  - [ ] bowtie
  - [ ] necktie
  - [ ] red glasses
  - [ ] fluffy scarf
  - [ ] engineer goggles
  - [ ] eyepatch
  - [ ] wicked eyepatch
  - [ ] red ribbons
  - [ ] pink flower bud
  - [ ] polka dot bows
  - [ ] blue butterfly
  - [ ] cat ears
  - [ ] witch pin
  - [ ] devil tail
  - [ ] kamui eye
  - [ ] googly eyes
  - [ ] four leaf clover
  - [ ] clock eye
  - [ ] unicorn horn
  - [ ] devil horns
  - [ ] hyper plus
  - [ ] botanist emblem
  - [ ] ancient mask
  - [ ] eerie mask
  - [ ] alien antenna
  - [ ] anaglyph glasses
  - [ ] orange shades
  - [ ] groucho glasses
  - [ ] thick eyebrows
  - [ ] lusitanic shield
  - [ ] tiny potato mask
  - [ ] questgiver mark
- [x] diva charm
- [x] flugel tiara
- [ ] golden laurel
- [x] cloak of virtue
- [x] cloak of sin
- [x] snowflake pendant
- [x] the spectator
- [x] tectonic girdle
- [x] pyroclast pendant
- [ ] monocle
- [x] crimson pendant
- [x] tiny planet
- [x] soujourner's/planestrider/globetrotter sash

### LINKED ISSUE #334: Cosmetic baubles in strange positions/orientations
Although not entirely unpleasant, my crotch was not the place I expected to see the puffy scarf. Now, if only it were flat vertically rather than being strangely erect. However, I was very distraught to find cat ears protruding from my eyes.

Minecraft 1.9.4
Forge 1.9.4-12.17.0.1954
Botania Unofficial r1.8-308 (also, the version still has the 1.8 prefix in 1.9)

### PR DESCRIPTION
**Pull request by yrsegal**
closes #49
closes #334 because it's a dupe

### CODE REVIEW

**Comment by williewillus** [comment]
This fixes em all and doesn't break the old ones?

**Comment by williewillus** [comment]
I haven't looked but also does it move off of third person right hand?

**Comment by yrsegal** [comment]
It shouldn't need to, right? If it does I'll fix it.

**Comment by williewillus** [comment]
I was thinking of moving towards GROUND.
Using THIRD PERSON in 1.8 made sense but now that it's handed if someone transforms those it could look weord

**Comment by yrsegal** [comment]
I kind of want to use NONE, is that ok?

**Comment by williewillus** [comment]
That's fine, yes
Change/recheck it everywhere ground or third person right is used for player renders

**Comment by yrsegal** [comment]
Got it, I'll change all the auxiliaries (and I guess the ones for NP, bleh)

**Comment by yrsegal** [comment]
ok, it uses NONE now, and also all of them have been checked to be close to or more correct than the 1.7 versions.

**Comment by yrsegal** [comment]
by 'More correct' I mean things which were offcenter and looked bad because of it have been polished. Yay for obsessiveness in visuals \o/

**Comment by williewillus** [comment]
<3

**Pull request merged**
