### PR TITLE
Add a flower crushing recipe

### LINKED ISSUE #215: Dyes from vanilla flowers, that are not from poppies and dandelions, don't count for a flower origened dye to make floral fertilizer

### PR DESCRIPTION
**Pull request by yrsegal**
Closes #215, kinda

### CODE REVIEW

**Comment by yrsegal** [comment]
@williewillus the only balance concern with this recipe: The result can be transmuted into mana powder. Can I assume this isn't a problem?

**Comment by williewillus** [comment]
533a287
(I didn't like how hacky this recipe looks. Better off just hardcoding them all)

**Comment by yrsegal** [comment]
ok ¯_(ツ)_/¯

**Comment by yrsegal** [comment]
it really isn't hacky, but whatever, so long as the solution exists

**Comment by williewillus** [comment]
Regex+iterating the oredict half a dozen times+ the doingFlowerRecipe hack
vs
14 standard shapeless recipe calls
:P

**Comment by yrsegal** [comment]
as long as it exists :P

**Pull request closed without merging**
