### PR TITLE
Fix NullPointerException with SmokeyQuartz disabled

### LINKED ISSUE #119: NullPointerException with SmokeyQuartz disabled
<pre>
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.8.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/17/16 5:54 PM
Description: Initializing game

java.lang.NullPointerException: at index 15
    at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
    at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:295)
    at vazkii.botania.client.core.handler.ModelHandler.registerStateMappers(ModelHandler.java:765)
    at vazkii.botania.client.core.handler.ModelHandler.registerModels(ModelHandler.java:143)
    at vazkii.botania.client.core.proxy.ClientProxy.preInit(ClientProxy.java:181)
    at vazkii.botania.common.Botania.preInit(Botania.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54) 
</pre>

### PR DESCRIPTION
**Pull request by Renari**
Fixes #119

### CODE REVIEW

**Comment by yrsegal** [comment]
rebase your commits down to a single commit, please. It's proper form :P

**Comment by Renari** [comment]
Sorry I'm not sure how to do that when I've tried it just makes two more commits.

**Comment by yrsegal** [comment]
git rebase, and then push with no fast forwards (google it if you don't know what fast forwarding is, it's not a well-known concept for most people :P)

**Comment by Renari** [comment]
That should do it I think?

**Comment by yrsegal** [comment]
why are some of willie's commits in there?

**Comment by Renari** [comment]
Sorry that was easier to fix than I thought.

**Comment by yrsegal** [comment]
ok, looks good!

**Comment by williewillus** [comment]
Your patch is a bit weird (has some of mine in it, did you edit manually)?
Anyhow, I've fixed this in my own commit, thanks for the contribution!

**Comment by Renari** [comment]
It's when I tried to rebase it merged one of your commits into mine.

**Pull request closed without merging**
