### PR TITLE
Mini Island "Optimized" Model

### PR DESCRIPTION
**Pull request by vladfrangu**
If I did this right, the New model **should** work. Testing would be required.

And I don't think I can test it out. I'll try to

Also, I've moved the grass for the main island to its file, instead of in the blockstate.

### CODE REVIEW

**Comment by vladfrangu** [comment]
I say fixed as in made it not-laggy

**Comment by vladfrangu** [comment]
And this is how it should look like: https://puu.sh/qG3GB/39479bbe04.png

**Comment by williewillus** [comment]
It doesn't match the shape of the original which was what I was going for. If what I'm working on right now still doesn't help much I'll look at this again.

**Comment by vladfrangu** [comment]
Did I mess up the shape? Theres a 10x10, a 8x8, 6x6, 4x4 and a 2x2. If it needs to be slightly different, I can change it

**Comment by vladfrangu** [comment]
I can change it to a 1x1, 3x3, 5x5, 7x7 and a 9x9

**Comment by vladfrangu** [comment]
Just made a 9x9 top model. Textures can be changed if needed

**Comment by williewillus** [comment]
I finished mine up, but thanks for the offer anyway

**Pull request closed without merging**
