### PR TITLE
Iron out some kinks in the Bauble Box and Flower Pouch

### LINKED ISSUE #297: Crash when right clicking the bauble case in off hand.
http://pastebin.com/ma1VjKGQ

### PR DESCRIPTION
**Pull request by howtonotwin**
- Remove a debug `println()` in ContainerBaubleBox.
- Resize `InventoryBaubleBox.FALLBACK_INVENTORY` and change
  `getSizeInventory()` to 36 instead of 16.
- Disallow opening the Bauble Case or the Flower Pouch from
  the offhand.

Fixes #297

### CODE REVIEW

**Comment by howtonotwin** [comment]
If we only had one or two more committers right now, we could probably turn the commit history into spaghetti. <sup><sub>Yum, spaghetti... mmmmmMMMmmmMmmmm<sub>mmmm<sup>mmm</sup></sub></sub></sup>
Actually, if I squint really hard, `gitk --all` looks kinda like a fork. <h1>THE FLYING SPAGHETTI MONSTER APPROVES OF OUR ENDEAVORS!</h1>

**Comment by williewillus** [comment]
Why are we resizing the fallback? It is 16 because the bauble box itself has 16

**Comment by yrsegal** [comment]
Doesn't it have more slots? 24, to be exact.

**Comment by williewillus** [comment]
Oh, I misread it was the bauble inv getting resized

**Comment by howtonotwin** [comment]
The fallback being small was the root cause of the issue, sometimes `stack` in `getInventory()` is `null`, then FALLBACK_INVENTORY is too small and throws an exception when `getStackInSlot(16)` is called. `stack` only seems to be null in the offhand, but that doesn't matter much, as if you do open the case in the offhand it closes instantly.

Though the case **does** have only 24 slots, but I must have gotten confused by [this line](http://github.com/williewillus/Botania/blob/78f296d0cf0831520ac0036787031774b5c17b89/src/main/java/vazkii/botania/common/item/ItemBaubleBox.java#L48).

Also, completely off topic, but is there a reason that `Botania_*.launch` aren't in the `.gitignore`?

**Comment by williewillus** [comment]
I'm probably going to redo them both using caps anyway

**Comment by williewillus** [comment]
02cfe14

**Pull request closed without merging**
