### PR TITLE
Add a ManaUpgradeRecipe.

### PR DESCRIPTION
**Pull request by yrsegal**
third pr for recipes, yay

### CODE REVIEW

**Comment by williewillus** [comment]
you should probably explain what it does :P

**Comment by yrsegal** [comment]
oh, ok :P 
When crafting anything with a mana tablet, it will give the internal storage of mana to the crafted item.

**Comment by yrsegal** [comment]
this applies, as of this PR, to the Band of Mana, the Greater Band of Mana, and the Terra Shatterer.

**Comment by williewillus** [comment]
cool, cool
I'll look at these all at once when I have time >.> (tonight/tomorrow night? at worst this weekend)

**Comment by yrsegal** [comment]
watch there be two more by then <.<

**Comment by yrsegal** [comment]
By the way, YES, these recipes which aren't in the sorter are deliberate. The RecipeSorter will sort things which extend ShapedOreRecipe, etc just like instances of ShapedOreRecipe itself.

**Comment by yrsegal** [comment]
@williewillus if you merge this, close #225.

**Comment by williewillus** [comment]
Resolve merge conflicts and I'll pull

**Comment by yrsegal** [comment]
ok

**Comment by yrsegal** [comment]
done

**Pull request merged**
