### PR TITLE
Limit BH Talisman to world height. Fixes #258

### LINKED ISSUE #258: Black hole talisman deletes items when trying to place blocks above world limit
You cannot place blocks above the world limit, but the black hole talisman believes it can.

### PR DESCRIPTION
**Pull request by howtonotwin**
Sorry for the mess :fearful:

### CODE REVIEW

**Comment by williewillus** [comment]
You've tested this and it fixes the bug?
As far as I remember isReplaceable only is for things like tall grass letting you place a block in it.

**Comment by howtonotwin** [comment]
It's the same logic `ItemBlock.onItemUse()` uses, and yes it is tested. And the fact that it only works for things like water and grass is desired, because most blocks would deflect the block placement upwards into the world limit, and those are the exceptions.

**Comment by williewillus** [comment]
I don't think that's it. The actual height check is done in the first 3 lines of setBlockState

**Comment by howtonotwin** [comment]
Yes, but my heightcheck is the [2<sup>nd</sup> edited line](https://github.com/williewillus/Botania/pull/315/files#diff-4eb34b9dacda508bae46c3079f258ee8R120). The first one calculates the final position of the block. `pos` is the position of the block clicked (i.e. the one in the wireframe). If `bBlock.isReplaceable()`, the new block gets placed into `pos` and replaces whatever is in there. If not, then `pos` is offset by `side`. This is important, because when the talisman is used on the _top_ face of a block at Y = 255, (the only way to "place" a block at Y = 256) `pos.getY() == 255`. `correctedPos` is then deflected one block up (`pos.offset(side)`), so that `correctedPos.getY() == 256`. Note that testing for `pos.getY() == 255` is faulty logic because that wouldn't allow a block to be placed on the side of a block at Y = 255. Also note that `correctedPos` is not passed to `onItemUse()`, `pos` is.

Also, Minecraft's own code seems a bit faulty to me. Even if the actual placing of the block fails, it gets ignored (see `ItemBlock:55-67`, even if `placeBlockAt()` is false, it returns `EnumActionResult.SUCCESS`).

**Comment by williewillus** [comment]
I see, I misread it at first. Thanks!

**Pull request merged**
