### PR TITLE
Allow Elven Trade recipes to have multiple outputs

### PR DESCRIPTION
**Pull request by shadowfacts**
This allows for Elven Trade recipes that have multiple outputs which is necessary for the addon I'm making based on Vazkii's [Elven Charter](https://i.imgur.com/OOu8mLu.png) idea.

This PR retains the original API method so any mods attempting to add Elven Trade recipes should still work properly. They may break if they're using a custom `RecipeElvenTrade` implementation. 

This also modifies the Lexica Elven Trade recipe page to render multiple outputs. The "bubble" in the texture has been removed to accommodate this. 

This is an example of how the updated Lexica page looks:

### CODE REVIEW

**Comment by yrsegal** [comment]
Does it work in JEI correctly?

**Comment by shadowfacts** [comment]
Now it does:

**Comment by williewillus** [comment]
was there no way to keep the little bubble in the gui in a way that looked nice? just wondering

code looks great

**Comment by shadowfacts** [comment]
Maybe, but it probably wouldn't look as nice as the original and IMO would require more effort than it's worth. I'd have to draw 4 quads for the corners and 4 more quads for the edges, and even then, it'd be a rounded-rect not a circle like the original.

**Comment by williewillus** [comment]
cool, it's not a big deal then

**Pull request merged**
